version: "3"

services:
    pokitoki-advanced:
        container_name: pokitoki-advanced
        command: python3 -m bot.bot
        restart: unless-stopped
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ./config.yml:/code/config.yml
            - data:/code/data

volumes:
    data:
